name: ewb-energy-model
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - tensorflow
  - keras
  - notebook
  - pip
  - pip:
      - pmdarima
      - shap
      - influxdb
