name: my-ml-env
channels:
  - defaults
dependencies:
  - python=3.11.5
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - statsmodels=0.14.0
  - jupyterlab=3.6.3
  - notebook=6.5.4
  - ipywidgets=8.0.4
  - plotly=5.9.0
  - tensorflow=2.17.0
  - keras=3.5.0
  - pytables=3.8.0
  - openpyxl=3.0.10
  - pip
  - pip:
      - shap==0.46.0
      - pmdarima==2.0.4
      - influxdb==5.3.2
      - influxdb-client==1.48.0
      - torch==2.5.1
      - torchvision==0.20.1+cpu
      - torchaudio==2.5.1+cpu
