name: ewb-energy-model
channels:
  - defaults
dependencies:
  - python=3.11.7
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - statsmodels=0.14.0
  - tensorflow
  - keras
  - notebook
  - pip=23.3.1
  - pip:
      - pmdarima
      - shap
      - influxdb
