name: dm4bem-env

channels:
  - conda-forge

dependencies:
  - absl-py==2.1.0
    - astunparse==1.6.3
    - cython==3.0.11
    - flatbuffers==24.3.25
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.65.4
    - h5py==3.11.0
    - influxdb==5.3.2
    - influxdb-client==1.48.0
    - keras==3.5.0
    - libclang==18.1.1
    - ml-dtypes==0.4.0
    - namex==0.0.8
    - opt-einsum==3.3.0
    - optree==0.12.1
    - pmdarima==2.0.4
      - protobuf==4.25.4
      - reactivex==4.0.4
      - rich==13.7.1
      - shap==0.46.0
      - slicer==0.0.8
      - sympy==1.13.1
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-intel==2.17.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - torch==2.5.1
      - torchaudio==2.5.1+cpu
      - torchvision==0.20.1+cpu
      - typing-extensions==4.12.2
